# GENERATED by generate_client.py — do not edit
"""Python client for the DeviceKit ``/api/v1`` surface.

Generated from the OpenAPI spec ('DeviceKit Public API', api version v1).
Regenerate with ``python cli/generate_client.py`` (see that script for options).

Auth: pass a scoped ``dk_`` API key (sent as ``X-API-Key``) or leave it unset when
the backend runs in solo/dev mode. Errors surface as :class:`DeviceKitApiError`
carrying the HTTP status and the server's ``{'error': ...}`` message.
"""
from urllib.parse import quote

import requests

__all__ = ['DeviceKitClient', 'DeviceKitApiError']


def _p(value):
    """Encode one path parameter."""
    return quote(str(value), safe='')


class DeviceKitApiError(Exception):
    """Non-2xx API response: ``.status`` (int) and ``.message`` (server error text)."""

    def __init__(self, status, message):
        super().__init__(f'HTTP {status}: {message}')
        self.status = status
        self.message = message


class DeviceKitClient:
    """Thin requests-based client; one method per documented (path, verb) pair."""

    def __init__(self, base_url='http://127.0.0.1:5050', api_key=None, timeout=60):
        self.base_url = base_url.rstrip('/')
        self.timeout = timeout
        self.session = requests.Session()
        self.session.headers['Accept'] = 'application/json'
        if api_key:
            self.session.headers['X-API-Key'] = api_key

    def _request(self, method, path, params=None, json=None):
        resp = self.session.request(method, self.base_url + path, params=params,
                                    json=json, timeout=self.timeout)
        try:
            body = resp.json()
        except ValueError:
            body = None
        if not 200 <= resp.status_code < 300:
            if isinstance(body, dict) and body.get('error'):
                message = body['error']
            else:
                message = (resp.text or resp.reason or '').strip()[:300]
            raise DeviceKitApiError(resp.status_code, message)
        return body if body is not None else resp.text

    def get_index(self, params=None):
        """Public API discovery: version, auth schemes, and where to find the spec.

        GET /api/v1
        """
        return self._request('GET', '/api/v1', params=params)

    def get_actions(self, params=None):
        """List the invocable actions with their JSON schemas and required scopes.

        GET /api/v1/actions
        Requires scope `devices:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', '/api/v1/actions', params=params)

    def post_actions_invoke(self, params=None, json=None):
        """Invoke one curated action on a device; writes wait on the confirmation gate.

        POST /api/v1/actions/invoke
        """
        return self._request('POST', '/api/v1/actions/invoke', params=params, json=json)

    def get_activities(self, params=None):
        """GET /api/v1/activities
        """
        return self._request('GET', '/api/v1/activities', params=params)

    def get_agent_apk_status(self, params=None):
        """Check cached APK version and latest release info.

        GET /api/v1/agent-apk/status
        """
        return self._request('GET', '/api/v1/agent-apk/status', params=params)

    def post_agent_device_command_result(self, params=None, json=None):
        """Agent posts the result of a dispatched command back to the waiting caller.

        POST /api/v1/agent-device/command-result
        """
        return self._request('POST', '/api/v1/agent-device/command-result', params=params, json=json)

    def post_agent_device_enroll(self, params=None, json=None):
        """Agent starts enrollment; receives a pairing code to display for an operator.

        POST /api/v1/agent-device/enroll
        """
        return self._request('POST', '/api/v1/agent-device/enroll', params=params, json=json)

    def get_agent_device_enroll_by_pairing_id(self, pairing_id, params=None):
        """Agent polls until an operator claims the code, then gets its secret once.

        GET /api/v1/agent-device/enroll/{pairing_id}
        """
        return self._request('GET', f'/api/v1/agent-device/enroll/{_p(pairing_id)}', params=params)

    def post_agent_device_event(self, params=None, json=None):
        """POST /api/v1/agent-device/event
        """
        return self._request('POST', '/api/v1/agent-device/event', params=params, json=json)

    def get_agent_device_events(self, params=None):
        """GET /api/v1/agent-device/events
        """
        return self._request('GET', '/api/v1/agent-device/events', params=params)

    def post_agent_device_heartbeat(self, params=None, json=None):
        """POST /api/v1/agent-device/heartbeat
        """
        return self._request('POST', '/api/v1/agent-device/heartbeat', params=params, json=json)

    def post_agent_device_register(self, params=None, json=None):
        """POST /api/v1/agent-device/register
        """
        return self._request('POST', '/api/v1/agent-device/register', params=params, json=json)

    def post_agent_device_state(self, params=None, json=None):
        """POST /api/v1/agent-device/state
        """
        return self._request('POST', '/api/v1/agent-device/state', params=params, json=json)

    def get_agent_device_status(self, params=None):
        """GET /api/v1/agent-device/status
        """
        return self._request('GET', '/api/v1/agent-device/status', params=params)

    def get_agent_device_by_device_id_capabilities(self, device_id, params=None):
        """GET /api/v1/agent-device/{device_id}/capabilities
        """
        return self._request('GET', f'/api/v1/agent-device/{_p(device_id)}/capabilities', params=params)

    def get_agent_device_by_device_id_command_history(self, device_id, params=None):
        """GET /api/v1/agent-device/{device_id}/command-history
        """
        return self._request('GET', f'/api/v1/agent-device/{_p(device_id)}/command-history', params=params)

    def get_agent_device_by_device_id_commands(self, device_id, params=None):
        """Agent poll: drain the server->agent command queue for this device.

        GET /api/v1/agent-device/{device_id}/commands
        """
        return self._request('GET', f'/api/v1/agent-device/{_p(device_id)}/commands', params=params)

    def post_agent_device_by_device_id_dispatch(self, device_id, params=None, json=None):
        """Operator-side: dispatch a command to a device and block for the result. Persisted

        POST /api/v1/agent-device/{device_id}/dispatch
        """
        return self._request('POST', f'/api/v1/agent-device/{_p(device_id)}/dispatch', params=params, json=json)

    def get_agent_device_by_device_id_metrics(self, device_id, params=None):
        """Return raw agent-sourced metrics for a device.

        GET /api/v1/agent-device/{device_id}/metrics
        """
        return self._request('GET', f'/api/v1/agent-device/{_p(device_id)}/metrics', params=params)

    def post_agent_device_by_device_id_rotate_key(self, device_id, params=None, json=None):
        """Start zero-downtime key rotation: stage a new secret (both remain valid until the

        POST /api/v1/agent-device/{device_id}/rotate-key
        """
        return self._request('POST', f'/api/v1/agent-device/{_p(device_id)}/rotate-key', params=params, json=json)

    def post_agent_device_by_device_id_rotate_key_complete(self, device_id, params=None, json=None):
        """Promote the pending secret to active and retire the old one.

        POST /api/v1/agent-device/{device_id}/rotate-key/complete
        """
        return self._request('POST', f'/api/v1/agent-device/{_p(device_id)}/rotate-key/complete', params=params, json=json)

    def post_agent_devices_claim(self, params=None, json=None):
        """Dashboard: operator claims a pairing code, enrolling the device.

        POST /api/v1/agent-devices/claim
        """
        return self._request('POST', '/api/v1/agent-devices/claim', params=params, json=json)

    def get_agent_devices_pending(self, params=None):
        """Dashboard: list agents awaiting a claim.

        GET /api/v1/agent-devices/pending
        """
        return self._request('GET', '/api/v1/agent-devices/pending', params=params)

    def get_agent_status(self, params=None):
        """GET /api/v1/agent/status
        """
        return self._request('GET', '/api/v1/agent/status', params=params)

    def post_agent_by_device_id_command(self, device_id, params=None, json=None):
        """POST /api/v1/agent/{device_id}/command
        """
        return self._request('POST', f'/api/v1/agent/{_p(device_id)}/command', params=params, json=json)

    def get_agent_by_device_id_commands(self, device_id, params=None):
        """GET /api/v1/agent/{device_id}/commands
        """
        return self._request('GET', f'/api/v1/agent/{_p(device_id)}/commands', params=params)

    def get_agent_by_device_id_logs(self, device_id, params=None):
        """GET /api/v1/agent/{device_id}/logs
        """
        return self._request('GET', f'/api/v1/agent/{_p(device_id)}/logs', params=params)

    def post_agent_by_device_id_start(self, device_id, params=None, json=None):
        """POST /api/v1/agent/{device_id}/start
        """
        return self._request('POST', f'/api/v1/agent/{_p(device_id)}/start', params=params, json=json)

    def get_agent_by_device_id_status(self, device_id, params=None):
        """GET /api/v1/agent/{device_id}/status
        """
        return self._request('GET', f'/api/v1/agent/{_p(device_id)}/status', params=params)

    def post_agent_by_device_id_stop(self, device_id, params=None, json=None):
        """POST /api/v1/agent/{device_id}/stop
        """
        return self._request('POST', f'/api/v1/agent/{_p(device_id)}/stop', params=params, json=json)

    def get_ai_hub_health(self, params=None):
        """Proxy probe of the configured prompture-hub: liveness + key-scoped model

        GET /api/v1/ai/hub/health
        """
        return self._request('GET', '/api/v1/ai/hub/health', params=params)

    def get_alerts(self, params=None):
        """GET /api/v1/alerts
        """
        return self._request('GET', '/api/v1/alerts', params=params)

    def post_alerts(self, params=None, json=None):
        """POST /api/v1/alerts
        """
        return self._request('POST', '/api/v1/alerts', params=params, json=json)

    def put_alerts_by_alert_id_dismiss(self, alert_id, params=None, json=None):
        """PUT /api/v1/alerts/{alert_id}/dismiss
        """
        return self._request('PUT', f'/api/v1/alerts/{_p(alert_id)}/dismiss', params=params, json=json)

    def get_api_keys(self, params=None):
        """GET /api/v1/api-keys
        """
        return self._request('GET', '/api/v1/api-keys', params=params)

    def post_api_keys(self, params=None, json=None):
        """POST /api/v1/api-keys
        """
        return self._request('POST', '/api/v1/api-keys', params=params, json=json)

    def get_api_keys_scopes(self, params=None):
        """GET /api/v1/api-keys/scopes
        """
        return self._request('GET', '/api/v1/api-keys/scopes', params=params)

    def get_api_keys_by_key_id(self, key_id, params=None):
        """GET /api/v1/api-keys/{key_id}
        """
        return self._request('GET', f'/api/v1/api-keys/{_p(key_id)}', params=params)

    def delete_api_keys_by_key_id(self, key_id, params=None):
        """DELETE /api/v1/api-keys/{key_id}
        """
        return self._request('DELETE', f'/api/v1/api-keys/{_p(key_id)}', params=params)

    def post_api_keys_by_key_id_rotate(self, key_id, params=None, json=None):
        """POST /api/v1/api-keys/{key_id}/rotate
        """
        return self._request('POST', f'/api/v1/api-keys/{_p(key_id)}/rotate', params=params, json=json)

    def get_audit(self, params=None):
        """GET /api/v1/audit
        """
        return self._request('GET', '/api/v1/audit', params=params)

    def post_auth_2fa_confirm(self, params=None, json=None):
        """POST /api/v1/auth/2fa/confirm
        """
        return self._request('POST', '/api/v1/auth/2fa/confirm', params=params, json=json)

    def post_auth_2fa_disable(self, params=None, json=None):
        """POST /api/v1/auth/2fa/disable
        """
        return self._request('POST', '/api/v1/auth/2fa/disable', params=params, json=json)

    def post_auth_2fa_setup(self, params=None, json=None):
        """POST /api/v1/auth/2fa/setup
        """
        return self._request('POST', '/api/v1/auth/2fa/setup', params=params, json=json)

    def post_auth_login(self, params=None, json=None):
        """POST /api/v1/auth/login
        """
        return self._request('POST', '/api/v1/auth/login', params=params, json=json)

    def post_auth_logout(self, params=None, json=None):
        """POST /api/v1/auth/logout
        """
        return self._request('POST', '/api/v1/auth/logout', params=params, json=json)

    def get_auth_permissions_schema(self, params=None):
        """GET /api/v1/auth/permissions/schema
        """
        return self._request('GET', '/api/v1/auth/permissions/schema', params=params)

    def get_auth_session(self, params=None):
        """GET /api/v1/auth/session
        """
        return self._request('GET', '/api/v1/auth/session', params=params)

    def get_automations(self, params=None):
        """GET /api/v1/automations
        Requires scope `automations:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', '/api/v1/automations', params=params)

    def post_automations(self, params=None, json=None):
        """POST /api/v1/automations
        Requires scope `automations:write` when authenticated with a `dk_` API key.
        """
        return self._request('POST', '/api/v1/automations', params=params, json=json)

    def post_automations_generate(self, params=None, json=None):
        """POST /api/v1/automations/generate
        Requires scope `automations:write` when authenticated with a `dk_` API key.
        """
        return self._request('POST', '/api/v1/automations/generate', params=params, json=json)

    def post_automations_import(self, params=None, json=None):
        """POST /api/v1/automations/import
        Requires scope `automations:write` when authenticated with a `dk_` API key.
        """
        return self._request('POST', '/api/v1/automations/import', params=params, json=json)

    def post_automations_record_action(self, params=None, json=None):
        """POST /api/v1/automations/record/action
        Requires scope `automations:write` when authenticated with a `dk_` API key.
        """
        return self._request('POST', '/api/v1/automations/record/action', params=params, json=json)

    def post_automations_record_start(self, params=None, json=None):
        """POST /api/v1/automations/record/start
        Requires scope `automations:write` when authenticated with a `dk_` API key.
        """
        return self._request('POST', '/api/v1/automations/record/start', params=params, json=json)

    def post_automations_record_stop(self, params=None, json=None):
        """POST /api/v1/automations/record/stop
        Requires scope `automations:write` when authenticated with a `dk_` API key.
        """
        return self._request('POST', '/api/v1/automations/record/stop', params=params, json=json)

    def post_automations_refine_step(self, params=None, json=None):
        """POST /api/v1/automations/refine-step
        Requires scope `automations:write` when authenticated with a `dk_` API key.
        """
        return self._request('POST', '/api/v1/automations/refine-step', params=params, json=json)

    def get_automations_runs(self, params=None):
        """GET /api/v1/automations/runs
        Requires scope `automations:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', '/api/v1/automations/runs', params=params)

    def get_automations_runs_by_run_id(self, run_id, params=None):
        """GET /api/v1/automations/runs/{run_id}
        Requires scope `automations:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', f'/api/v1/automations/runs/{_p(run_id)}', params=params)

    def post_automations_runs_by_run_id_cancel(self, run_id, params=None, json=None):
        """POST /api/v1/automations/runs/{run_id}/cancel
        Requires scope `automations:run` when authenticated with a `dk_` API key.
        """
        return self._request('POST', f'/api/v1/automations/runs/{_p(run_id)}/cancel', params=params, json=json)

    def get_automations_runs_by_run_id_regression_report(self, run_id, params=None):
        """GET /api/v1/automations/runs/{run_id}/regression-report
        """
        return self._request('GET', f'/api/v1/automations/runs/{_p(run_id)}/regression-report', params=params)

    def get_automations_runs_by_run_id_screenshots_by_step_index(self, run_id, step_index, params=None):
        """GET /api/v1/automations/runs/{run_id}/screenshots/{step_index}
        Requires scope `automations:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', f'/api/v1/automations/runs/{_p(run_id)}/screenshots/{_p(step_index)}', params=params)

    def get_automations_schedules(self, params=None):
        """GET /api/v1/automations/schedules
        Requires scope `automations:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', '/api/v1/automations/schedules', params=params)

    def post_automations_schedules(self, params=None, json=None):
        """POST /api/v1/automations/schedules
        Requires scope `automations:write` when authenticated with a `dk_` API key.
        """
        return self._request('POST', '/api/v1/automations/schedules', params=params, json=json)

    def put_automations_schedules_by_schedule_id(self, schedule_id, params=None, json=None):
        """PUT /api/v1/automations/schedules/{schedule_id}
        Requires scope `automations:write` when authenticated with a `dk_` API key.
        """
        return self._request('PUT', f'/api/v1/automations/schedules/{_p(schedule_id)}', params=params, json=json)

    def delete_automations_schedules_by_schedule_id(self, schedule_id, params=None):
        """DELETE /api/v1/automations/schedules/{schedule_id}
        Requires scope `automations:write` when authenticated with a `dk_` API key.
        """
        return self._request('DELETE', f'/api/v1/automations/schedules/{_p(schedule_id)}', params=params)

    def get_automations_step_types(self, params=None):
        """GET /api/v1/automations/step-types
        Requires scope `automations:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', '/api/v1/automations/step-types', params=params)

    def get_automations_by_automation_id(self, automation_id, params=None):
        """GET /api/v1/automations/{automation_id}
        Requires scope `automations:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', f'/api/v1/automations/{_p(automation_id)}', params=params)

    def put_automations_by_automation_id(self, automation_id, params=None, json=None):
        """PUT /api/v1/automations/{automation_id}
        Requires scope `automations:write` when authenticated with a `dk_` API key.
        """
        return self._request('PUT', f'/api/v1/automations/{_p(automation_id)}', params=params, json=json)

    def delete_automations_by_automation_id(self, automation_id, params=None):
        """DELETE /api/v1/automations/{automation_id}
        Requires scope `automations:write` when authenticated with a `dk_` API key.
        """
        return self._request('DELETE', f'/api/v1/automations/{_p(automation_id)}', params=params)

    def get_automations_by_automation_id_baselines(self, automation_id, params=None):
        """GET /api/v1/automations/{automation_id}/baselines
        """
        return self._request('GET', f'/api/v1/automations/{_p(automation_id)}/baselines', params=params)

    def post_automations_by_automation_id_baselines(self, automation_id, params=None, json=None):
        """POST /api/v1/automations/{automation_id}/baselines
        """
        return self._request('POST', f'/api/v1/automations/{_p(automation_id)}/baselines', params=params, json=json)

    def get_automations_by_automation_id_baselines_by_baseline_id(self, automation_id, baseline_id, params=None):
        """GET /api/v1/automations/{automation_id}/baselines/{baseline_id}
        """
        return self._request('GET', f'/api/v1/automations/{_p(automation_id)}/baselines/{_p(baseline_id)}', params=params)

    def put_automations_by_automation_id_baselines_by_baseline_id(self, automation_id, baseline_id, params=None, json=None):
        """PUT /api/v1/automations/{automation_id}/baselines/{baseline_id}
        """
        return self._request('PUT', f'/api/v1/automations/{_p(automation_id)}/baselines/{_p(baseline_id)}', params=params, json=json)

    def delete_automations_by_automation_id_baselines_by_baseline_id(self, automation_id, baseline_id, params=None):
        """DELETE /api/v1/automations/{automation_id}/baselines/{baseline_id}
        """
        return self._request('DELETE', f'/api/v1/automations/{_p(automation_id)}/baselines/{_p(baseline_id)}', params=params)

    def post_automations_by_automation_id_baselines_by_baseline_id_compare(self, automation_id, baseline_id, params=None, json=None):
        """Compare a device's current screenshot against a baseline.

        POST /api/v1/automations/{automation_id}/baselines/{baseline_id}/compare
        """
        return self._request('POST', f'/api/v1/automations/{_p(automation_id)}/baselines/{_p(baseline_id)}/compare', params=params, json=json)

    def get_automations_by_automation_id_baselines_by_baseline_id_image(self, automation_id, baseline_id, params=None):
        """GET /api/v1/automations/{automation_id}/baselines/{baseline_id}/image
        """
        return self._request('GET', f'/api/v1/automations/{_p(automation_id)}/baselines/{_p(baseline_id)}/image', params=params)

    def post_automations_by_automation_id_clone(self, automation_id, params=None, json=None):
        """POST /api/v1/automations/{automation_id}/clone
        Requires scope `automations:write` when authenticated with a `dk_` API key.
        """
        return self._request('POST', f'/api/v1/automations/{_p(automation_id)}/clone', params=params, json=json)

    def get_automations_by_automation_id_explain(self, automation_id, params=None):
        """GET /api/v1/automations/{automation_id}/explain
        Requires scope `automations:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', f'/api/v1/automations/{_p(automation_id)}/explain', params=params)

    def get_automations_by_automation_id_export(self, automation_id, params=None):
        """GET /api/v1/automations/{automation_id}/export
        Requires scope `automations:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', f'/api/v1/automations/{_p(automation_id)}/export', params=params)

    def post_automations_by_automation_id_run(self, automation_id, params=None, json=None):
        """POST /api/v1/automations/{automation_id}/run
        Requires scope `automations:run` when authenticated with a `dk_` API key.
        """
        return self._request('POST', f'/api/v1/automations/{_p(automation_id)}/run', params=params, json=json)

    def get_config(self, params=None):
        """GET /api/v1/config
        """
        return self._request('GET', '/api/v1/config', params=params)

    def put_config(self, params=None, json=None):
        """PUT /api/v1/config
        """
        return self._request('PUT', '/api/v1/config', params=params, json=json)

    def get_dashboard_stats(self, params=None):
        """GET /api/v1/dashboard/stats
        """
        return self._request('GET', '/api/v1/dashboard/stats', params=params)

    def get_debug_bundles(self, params=None):
        """List all debug bundles with optional filters.

        GET /api/v1/debug-bundles
        """
        return self._request('GET', '/api/v1/debug-bundles', params=params)

    def get_debug_bundles_share_by_token(self, token, params=None):
        """Download a debug bundle via share token.

        GET /api/v1/debug-bundles/share/{token}
        """
        return self._request('GET', f'/api/v1/debug-bundles/share/{_p(token)}', params=params)

    def get_debug_bundles_by_bundle_id(self, bundle_id, params=None):
        """Get debug bundle metadata.

        GET /api/v1/debug-bundles/{bundle_id}
        """
        return self._request('GET', f'/api/v1/debug-bundles/{_p(bundle_id)}', params=params)

    def delete_debug_bundles_by_bundle_id(self, bundle_id, params=None):
        """Delete a debug bundle.

        DELETE /api/v1/debug-bundles/{bundle_id}
        """
        return self._request('DELETE', f'/api/v1/debug-bundles/{_p(bundle_id)}', params=params)

    def post_debug_bundles_by_bundle_id_analyze(self, bundle_id, params=None, json=None):
        """Trigger AI analysis of a debug bundle.

        POST /api/v1/debug-bundles/{bundle_id}/analyze
        """
        return self._request('POST', f'/api/v1/debug-bundles/{_p(bundle_id)}/analyze', params=params, json=json)

    def get_debug_bundles_by_bundle_id_download(self, bundle_id, params=None):
        """Download debug bundle as ZIP.

        GET /api/v1/debug-bundles/{bundle_id}/download
        """
        return self._request('GET', f'/api/v1/debug-bundles/{_p(bundle_id)}/download', params=params)

    def post_debug_bundles_by_bundle_id_share(self, bundle_id, params=None, json=None):
        """Generate a shareable link for a debug bundle.

        POST /api/v1/debug-bundles/{bundle_id}/share
        """
        return self._request('POST', f'/api/v1/debug-bundles/{_p(bundle_id)}/share', params=params, json=json)

    def get_device_commands(self, params=None):
        """Fleet-wide device-action history.

        GET /api/v1/device-commands
        """
        return self._request('GET', '/api/v1/device-commands', params=params)

    def get_devices(self, params=None):
        """GET /api/v1/devices
        """
        return self._request('GET', '/api/v1/devices', params=params)

    def get_devices_available(self, params=None):
        """GET /api/v1/devices/available
        Requires scope `devices:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', '/api/v1/devices/available', params=params)

    def get_devices_by_device_id(self, device_id, params=None):
        """GET /api/v1/devices/{device_id}
        """
        return self._request('GET', f'/api/v1/devices/{_p(device_id)}', params=params)

    def post_devices_by_device_id_adb(self, device_id, params=None, json=None):
        """POST /api/v1/devices/{device_id}/adb
        Requires scope `devices:command` when authenticated with a `dk_` API key.
        """
        return self._request('POST', f'/api/v1/devices/{_p(device_id)}/adb', params=params, json=json)

    def get_devices_by_device_id_agent_audit(self, device_id, params=None):
        """GET /api/v1/devices/{device_id}/agent/audit
        """
        return self._request('GET', f'/api/v1/devices/{_p(device_id)}/agent/audit', params=params)

    def post_devices_by_device_id_agent_confirm(self, device_id, params=None, json=None):
        """POST /api/v1/devices/{device_id}/agent/confirm
        """
        return self._request('POST', f'/api/v1/devices/{_p(device_id)}/agent/confirm', params=params, json=json)

    def get_devices_by_device_id_agent_mode(self, device_id, params=None):
        """GET /api/v1/devices/{device_id}/agent/mode
        """
        return self._request('GET', f'/api/v1/devices/{_p(device_id)}/agent/mode', params=params)

    def put_devices_by_device_id_agent_mode(self, device_id, params=None, json=None):
        """PUT /api/v1/devices/{device_id}/agent/mode
        """
        return self._request('PUT', f'/api/v1/devices/{_p(device_id)}/agent/mode', params=params, json=json)

    def patch_devices_by_device_id_agent_model(self, device_id, params=None, json=None):
        """PATCH /api/v1/devices/{device_id}/agent/model
        """
        return self._request('PATCH', f'/api/v1/devices/{_p(device_id)}/agent/model', params=params, json=json)

    def get_devices_by_device_id_agent_pending(self, device_id, params=None):
        """GET /api/v1/devices/{device_id}/agent/pending
        """
        return self._request('GET', f'/api/v1/devices/{_p(device_id)}/agent/pending', params=params)

    def get_devices_by_device_id_agent_usage(self, device_id, params=None):
        """GET /api/v1/devices/{device_id}/agent/usage
        """
        return self._request('GET', f'/api/v1/devices/{_p(device_id)}/agent/usage', params=params)

    def get_devices_by_device_id_battery(self, device_id, params=None):
        """GET /api/v1/devices/{device_id}/battery
        Requires scope `devices:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', f'/api/v1/devices/{_p(device_id)}/battery', params=params)

    def delete_devices_by_device_id_conversation(self, device_id, params=None):
        """DELETE /api/v1/devices/{device_id}/conversation
        """
        return self._request('DELETE', f'/api/v1/devices/{_p(device_id)}/conversation', params=params)

    def get_devices_by_device_id_conversation_history(self, device_id, params=None):
        """GET /api/v1/devices/{device_id}/conversation/history
        """
        return self._request('GET', f'/api/v1/devices/{_p(device_id)}/conversation/history', params=params)

    def post_devices_by_device_id_debug_bundle(self, device_id, params=None, json=None):
        """On-demand debug bundle generation for a device.

        POST /api/v1/devices/{device_id}/debug-bundle
        """
        return self._request('POST', f'/api/v1/devices/{_p(device_id)}/debug-bundle', params=params, json=json)

    def get_devices_by_device_id_diagnostics(self, device_id, params=None):
        """Return device diagnostics, preferring agent-sourced metrics when available.

        GET /api/v1/devices/{device_id}/diagnostics
        Requires scope `devices:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', f'/api/v1/devices/{_p(device_id)}/diagnostics', params=params)

    def get_devices_by_device_id_files(self, device_id, params=None):
        """GET /api/v1/devices/{device_id}/files
        Requires scope `devices:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', f'/api/v1/devices/{_p(device_id)}/files', params=params)

    def get_devices_by_device_id_files_download(self, device_id, params=None):
        """Proxy file download from agent.

        GET /api/v1/devices/{device_id}/files/download
        Requires scope `devices:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', f'/api/v1/devices/{_p(device_id)}/files/download', params=params)

    def get_devices_by_device_id_files_search(self, device_id, params=None):
        """Proxy file search to agent.

        GET /api/v1/devices/{device_id}/files/search
        Requires scope `devices:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', f'/api/v1/devices/{_p(device_id)}/files/search', params=params)

    def post_devices_by_device_id_files_upload(self, device_id, params=None, json=None):
        """Proxy file upload to agent.

        POST /api/v1/devices/{device_id}/files/upload
        Requires scope `devices:command` when authenticated with a `dk_` API key.
        """
        return self._request('POST', f'/api/v1/devices/{_p(device_id)}/files/upload', params=params, json=json)

    def post_devices_by_device_id_lock(self, device_id, params=None, json=None):
        """POST /api/v1/devices/{device_id}/lock
        Requires scope `devices:write` when authenticated with a `dk_` API key.
        """
        return self._request('POST', f'/api/v1/devices/{_p(device_id)}/lock', params=params, json=json)

    def get_devices_by_device_id_metrics(self, device_id, params=None):
        """GET /api/v1/devices/{device_id}/metrics
        Requires scope `metrics:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', f'/api/v1/devices/{_p(device_id)}/metrics', params=params)

    def get_devices_by_device_id_metrics_sparkline(self, device_id, params=None):
        """GET /api/v1/devices/{device_id}/metrics/sparkline
        Requires scope `metrics:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', f'/api/v1/devices/{_p(device_id)}/metrics/sparkline', params=params)

    def post_devices_by_device_id_onboard(self, device_id, params=None, json=None):
        """Manually trigger agent APK onboarding for a device.

        POST /api/v1/devices/{device_id}/onboard
        """
        return self._request('POST', f'/api/v1/devices/{_p(device_id)}/onboard', params=params, json=json)

    def post_devices_by_device_id_press(self, device_id, params=None, json=None):
        """POST /api/v1/devices/{device_id}/press
        Requires scope `devices:command` when authenticated with a `dk_` API key.
        """
        return self._request('POST', f'/api/v1/devices/{_p(device_id)}/press', params=params, json=json)

    def get_devices_by_device_id_properties(self, device_id, params=None):
        """GET /api/v1/devices/{device_id}/properties
        Requires scope `devices:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', f'/api/v1/devices/{_p(device_id)}/properties', params=params)

    def post_devices_by_device_id_reboot(self, device_id, params=None, json=None):
        """POST /api/v1/devices/{device_id}/reboot
        Requires scope `devices:command` when authenticated with a `dk_` API key.
        """
        return self._request('POST', f'/api/v1/devices/{_p(device_id)}/reboot', params=params, json=json)

    def get_devices_by_device_id_screenshot(self, device_id, params=None):
        """GET /api/v1/devices/{device_id}/screenshot
        Requires scope `devices:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', f'/api/v1/devices/{_p(device_id)}/screenshot', params=params)

    def get_devices_by_device_id_sessions(self, device_id, params=None):
        """GET /api/v1/devices/{device_id}/sessions
        """
        return self._request('GET', f'/api/v1/devices/{_p(device_id)}/sessions', params=params)

    def post_devices_by_device_id_sessions_record(self, device_id, params=None, json=None):
        """POST /api/v1/devices/{device_id}/sessions/record
        """
        return self._request('POST', f'/api/v1/devices/{_p(device_id)}/sessions/record', params=params, json=json)

    def get_devices_by_device_id_sessions_by_session_id(self, device_id, session_id, params=None):
        """GET /api/v1/devices/{device_id}/sessions/{session_id}
        """
        return self._request('GET', f'/api/v1/devices/{_p(device_id)}/sessions/{_p(session_id)}', params=params)

    def post_devices_by_device_id_sessions_by_session_id_events(self, device_id, session_id, params=None, json=None):
        """POST /api/v1/devices/{device_id}/sessions/{session_id}/events
        """
        return self._request('POST', f'/api/v1/devices/{_p(device_id)}/sessions/{_p(session_id)}/events', params=params, json=json)

    def get_devices_by_device_id_sessions_by_session_id_frames_by_frame_index(self, device_id, session_id, frame_index, params=None):
        """GET /api/v1/devices/{device_id}/sessions/{session_id}/frames/{frame_index}
        """
        return self._request('GET', f'/api/v1/devices/{_p(device_id)}/sessions/{_p(session_id)}/frames/{_p(frame_index)}', params=params)

    def post_devices_by_device_id_sessions_by_session_id_stop(self, device_id, session_id, params=None, json=None):
        """POST /api/v1/devices/{device_id}/sessions/{session_id}/stop
        """
        return self._request('POST', f'/api/v1/devices/{_p(device_id)}/sessions/{_p(session_id)}/stop', params=params, json=json)

    def get_devices_by_device_id_stream(self, device_id, params=None):
        """GET /api/v1/devices/{device_id}/stream
        """
        return self._request('GET', f'/api/v1/devices/{_p(device_id)}/stream', params=params)

    def get_devices_by_device_id_stream_status(self, device_id, params=None):
        """GET /api/v1/devices/{device_id}/stream/status
        """
        return self._request('GET', f'/api/v1/devices/{_p(device_id)}/stream/status', params=params)

    def post_devices_by_device_id_swipe(self, device_id, params=None, json=None):
        """POST /api/v1/devices/{device_id}/swipe
        Requires scope `devices:command` when authenticated with a `dk_` API key.
        """
        return self._request('POST', f'/api/v1/devices/{_p(device_id)}/swipe', params=params, json=json)

    def get_devices_by_device_id_tags(self, device_id, params=None):
        """GET /api/v1/devices/{device_id}/tags
        Requires scope `devices:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', f'/api/v1/devices/{_p(device_id)}/tags', params=params)

    def put_devices_by_device_id_tags(self, device_id, params=None, json=None):
        """PUT /api/v1/devices/{device_id}/tags
        Requires scope `devices:write` when authenticated with a `dk_` API key.
        """
        return self._request('PUT', f'/api/v1/devices/{_p(device_id)}/tags', params=params, json=json)

    def post_devices_by_device_id_tap(self, device_id, params=None, json=None):
        """POST /api/v1/devices/{device_id}/tap
        Requires scope `devices:command` when authenticated with a `dk_` API key.
        """
        return self._request('POST', f'/api/v1/devices/{_p(device_id)}/tap', params=params, json=json)

    def get_devices_by_device_id_ui_hierarchy(self, device_id, params=None):
        """GET /api/v1/devices/{device_id}/ui-hierarchy
        Requires scope `devices:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', f'/api/v1/devices/{_p(device_id)}/ui-hierarchy', params=params)

    def post_devices_by_device_id_unlock(self, device_id, params=None, json=None):
        """POST /api/v1/devices/{device_id}/unlock
        Requires scope `devices:write` when authenticated with a `dk_` API key.
        """
        return self._request('POST', f'/api/v1/devices/{_p(device_id)}/unlock', params=params, json=json)

    def get_docs(self, params=None):
        """Rendered API reference (self-contained page over the generated spec).

        GET /api/v1/docs
        """
        return self._request('GET', '/api/v1/docs', params=params)

    def get_events_stream(self, params=None):
        """GET /api/v1/events/stream
        """
        return self._request('GET', '/api/v1/events/stream', params=params)

    def get_extensions(self, params=None):
        """GET /api/v1/extensions
        Requires scope `extensions:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', '/api/v1/extensions', params=params)

    def get_extensions_contributions(self, params=None):
        """Merged declarative UI contributions of every active extension (plan 04). The

        GET /api/v1/extensions/contributions
        Requires scope `extensions:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', '/api/v1/extensions/contributions', params=params)

    def post_extensions_install(self, params=None, json=None):
        """POST /api/v1/extensions/install
        Requires scope `extensions:admin` when authenticated with a `dk_` API key.
        """
        return self._request('POST', '/api/v1/extensions/install', params=params, json=json)

    def post_extensions_install_local(self, params=None, json=None):
        """Zip a working tree on disk through the real pipeline (dev loop).

        POST /api/v1/extensions/install-local
        Requires scope `extensions:admin` when authenticated with a `dk_` API key.
        """
        return self._request('POST', '/api/v1/extensions/install-local', params=params, json=json)

    def post_extensions_install_upload(self, params=None, json=None):
        """POST /api/v1/extensions/install-upload
        Requires scope `extensions:admin` when authenticated with a `dk_` API key.
        """
        return self._request('POST', '/api/v1/extensions/install-upload', params=params, json=json)

    def get_extensions_manifest_spec(self, params=None):
        """GET /api/v1/extensions/manifest-spec
        Requires scope `extensions:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', '/api/v1/extensions/manifest-spec', params=params)

    def post_extensions_preview(self, params=None, json=None):
        """POST /api/v1/extensions/preview
        Requires scope `extensions:admin` when authenticated with a `dk_` API key.
        """
        return self._request('POST', '/api/v1/extensions/preview', params=params, json=json)

    def get_extensions_registry(self, params=None):
        """GET /api/v1/extensions/registry
        Requires scope `extensions:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', '/api/v1/extensions/registry', params=params)

    def get_extensions_sdk_version(self, params=None):
        """GET /api/v1/extensions/sdk-version
        Requires scope `extensions:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', '/api/v1/extensions/sdk-version', params=params)

    def get_extensions_updates(self, params=None):
        """GET /api/v1/extensions/updates
        Requires scope `extensions:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', '/api/v1/extensions/updates', params=params)

    def get_extensions_by_slug(self, slug, params=None):
        """GET /api/v1/extensions/{slug}
        Requires scope `extensions:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', f'/api/v1/extensions/{_p(slug)}', params=params)

    def delete_extensions_by_slug(self, slug, params=None):
        """DELETE /api/v1/extensions/{slug}
        Requires scope `extensions:admin` when authenticated with a `dk_` API key.
        """
        return self._request('DELETE', f'/api/v1/extensions/{_p(slug)}', params=params)

    def get_extensions_by_slug_config(self, slug, params=None):
        """GET /api/v1/extensions/{slug}/config
        Requires scope `extensions:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', f'/api/v1/extensions/{_p(slug)}/config', params=params)

    def put_extensions_by_slug_config(self, slug, params=None, json=None):
        """PUT /api/v1/extensions/{slug}/config
        Requires scope `extensions:admin` when authenticated with a `dk_` API key.
        """
        return self._request('PUT', f'/api/v1/extensions/{_p(slug)}/config', params=params, json=json)

    def post_extensions_by_slug_disable(self, slug, params=None, json=None):
        """POST /api/v1/extensions/{slug}/disable
        Requires scope `extensions:admin` when authenticated with a `dk_` API key.
        """
        return self._request('POST', f'/api/v1/extensions/{_p(slug)}/disable', params=params, json=json)

    def post_extensions_by_slug_enable(self, slug, params=None, json=None):
        """POST /api/v1/extensions/{slug}/enable
        Requires scope `extensions:admin` when authenticated with a `dk_` API key.
        """
        return self._request('POST', f'/api/v1/extensions/{_p(slug)}/enable', params=params, json=json)

    def post_extensions_by_slug_update(self, slug, params=None, json=None):
        """POST /api/v1/extensions/{slug}/update
        Requires scope `extensions:admin` when authenticated with a `dk_` API key.
        """
        return self._request('POST', f'/api/v1/extensions/{_p(slug)}/update', params=params, json=json)

    def get_fleet_compare(self, params=None):
        """GET /api/v1/fleet/compare
        Requires scope `devices:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', '/api/v1/fleet/compare', params=params)

    def get_fleet_groups(self, params=None):
        """GET /api/v1/fleet/groups
        Requires scope `devices:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', '/api/v1/fleet/groups', params=params)

    def post_fleet_groups(self, params=None, json=None):
        """POST /api/v1/fleet/groups
        Requires scope `fleet:admin` when authenticated with a `dk_` API key.
        """
        return self._request('POST', '/api/v1/fleet/groups', params=params, json=json)

    def get_fleet_groups_by_group_id(self, group_id, params=None):
        """GET /api/v1/fleet/groups/{group_id}
        Requires scope `devices:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', f'/api/v1/fleet/groups/{_p(group_id)}', params=params)

    def put_fleet_groups_by_group_id(self, group_id, params=None, json=None):
        """PUT /api/v1/fleet/groups/{group_id}
        Requires scope `fleet:admin` when authenticated with a `dk_` API key.
        """
        return self._request('PUT', f'/api/v1/fleet/groups/{_p(group_id)}', params=params, json=json)

    def delete_fleet_groups_by_group_id(self, group_id, params=None):
        """DELETE /api/v1/fleet/groups/{group_id}
        Requires scope `fleet:admin` when authenticated with a `dk_` API key.
        """
        return self._request('DELETE', f'/api/v1/fleet/groups/{_p(group_id)}', params=params)

    def post_fleet_groups_by_group_id_bulk_command(self, group_id, params=None, json=None):
        """POST /api/v1/fleet/groups/{group_id}/bulk/command
        Requires scope `fleet:admin` when authenticated with a `dk_` API key.
        """
        return self._request('POST', f'/api/v1/fleet/groups/{_p(group_id)}/bulk/command', params=params, json=json)

    def post_fleet_groups_by_group_id_bulk_install(self, group_id, params=None, json=None):
        """POST /api/v1/fleet/groups/{group_id}/bulk/install
        Requires scope `fleet:admin` when authenticated with a `dk_` API key.
        """
        return self._request('POST', f'/api/v1/fleet/groups/{_p(group_id)}/bulk/install', params=params, json=json)

    def post_fleet_groups_by_group_id_bulk_reboot(self, group_id, params=None, json=None):
        """POST /api/v1/fleet/groups/{group_id}/bulk/reboot
        Requires scope `fleet:admin` when authenticated with a `dk_` API key.
        """
        return self._request('POST', f'/api/v1/fleet/groups/{_p(group_id)}/bulk/reboot', params=params, json=json)

    def post_fleet_groups_by_group_id_devices(self, group_id, params=None, json=None):
        """POST /api/v1/fleet/groups/{group_id}/devices
        Requires scope `fleet:admin` when authenticated with a `dk_` API key.
        """
        return self._request('POST', f'/api/v1/fleet/groups/{_p(group_id)}/devices', params=params, json=json)

    def delete_fleet_groups_by_group_id_devices_by_device_id(self, group_id, device_id, params=None):
        """DELETE /api/v1/fleet/groups/{group_id}/devices/{device_id}
        Requires scope `fleet:admin` when authenticated with a `dk_` API key.
        """
        return self._request('DELETE', f'/api/v1/fleet/groups/{_p(group_id)}/devices/{_p(device_id)}', params=params)

    def get_fleet_health(self, params=None):
        """GET /api/v1/fleet/health
        Requires scope `devices:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', '/api/v1/fleet/health', params=params)

    def get_fleet_metrics(self, params=None):
        """GET /api/v1/fleet/metrics
        Requires scope `metrics:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', '/api/v1/fleet/metrics', params=params)

    def get_fleet_metrics_sparklines(self, params=None):
        """GET /api/v1/fleet/metrics/sparklines
        Requires scope `metrics:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', '/api/v1/fleet/metrics/sparklines', params=params)

    def get_fleet_queries(self, params=None):
        """GET /api/v1/fleet/queries
        Requires scope `devices:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', '/api/v1/fleet/queries', params=params)

    def post_fleet_queries(self, params=None, json=None):
        """POST /api/v1/fleet/queries
        Requires scope `devices:write` when authenticated with a `dk_` API key.
        """
        return self._request('POST', '/api/v1/fleet/queries', params=params, json=json)

    def get_fleet_queries_by_query_id(self, query_id, params=None):
        """GET /api/v1/fleet/queries/{query_id}
        Requires scope `devices:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', f'/api/v1/fleet/queries/{_p(query_id)}', params=params)

    def put_fleet_queries_by_query_id(self, query_id, params=None, json=None):
        """PUT /api/v1/fleet/queries/{query_id}
        Requires scope `devices:write` when authenticated with a `dk_` API key.
        """
        return self._request('PUT', f'/api/v1/fleet/queries/{_p(query_id)}', params=params, json=json)

    def delete_fleet_queries_by_query_id(self, query_id, params=None):
        """DELETE /api/v1/fleet/queries/{query_id}
        Requires scope `devices:write` when authenticated with a `dk_` API key.
        """
        return self._request('DELETE', f'/api/v1/fleet/queries/{_p(query_id)}', params=params)

    def get_fleet_query(self, params=None):
        """Execute a fleet query expression against all devices.

        GET /api/v1/fleet/query
        Requires scope `devices:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', '/api/v1/fleet/query', params=params)

    def post_fleet_query_bulk_action(self, params=None, json=None):
        """Execute a bulk action on devices matching a query.

        POST /api/v1/fleet/query/bulk-action
        Requires scope `fleet:admin` when authenticated with a `dk_` API key.
        """
        return self._request('POST', '/api/v1/fleet/query/bulk-action', params=params, json=json)

    def get_fleet_query_fields(self, params=None):
        """Return supported query fields with descriptions.

        GET /api/v1/fleet/query/fields
        Requires scope `devices:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', '/api/v1/fleet/query/fields', params=params)

    def get_fleet_query_presets(self, params=None):
        """Return built-in preset queries.

        GET /api/v1/fleet/query/presets
        Requires scope `devices:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', '/api/v1/fleet/query/presets', params=params)

    def post_fleet_query_validate(self, params=None, json=None):
        """Validate a query expression without executing it.

        POST /api/v1/fleet/query/validate
        Requires scope `devices:read` when authenticated with a `dk_` API key.
        """
        return self._request('POST', '/api/v1/fleet/query/validate', params=params, json=json)

    def get_grants(self, params=None):
        """GET /api/v1/grants
        """
        return self._request('GET', '/api/v1/grants', params=params)

    def post_grants(self, params=None, json=None):
        """POST /api/v1/grants
        """
        return self._request('POST', '/api/v1/grants', params=params, json=json)

    def delete_grants_by_grant_id(self, grant_id, params=None):
        """DELETE /api/v1/grants/{grant_id}
        """
        return self._request('DELETE', f'/api/v1/grants/{_p(grant_id)}', params=params)

    def get_health(self, params=None):
        """GET /api/v1/health
        """
        return self._request('GET', '/api/v1/health', params=params)

    def get_invitations(self, params=None):
        """GET /api/v1/invitations
        """
        return self._request('GET', '/api/v1/invitations', params=params)

    def post_invitations(self, params=None, json=None):
        """POST /api/v1/invitations
        """
        return self._request('POST', '/api/v1/invitations', params=params, json=json)

    def delete_invitations_by_invitation_id(self, invitation_id, params=None):
        """DELETE /api/v1/invitations/{invitation_id}
        """
        return self._request('DELETE', f'/api/v1/invitations/{_p(invitation_id)}', params=params)

    def post_invitations_by_token_accept(self, token, params=None, json=None):
        """POST /api/v1/invitations/{token}/accept
        """
        return self._request('POST', f'/api/v1/invitations/{_p(token)}/accept', params=params, json=json)

    def get_invitations_by_token_preview(self, token, params=None):
        """GET /api/v1/invitations/{token}/preview
        """
        return self._request('GET', f'/api/v1/invitations/{_p(token)}/preview', params=params)

    def get_jobs(self, params=None):
        """GET /api/v1/jobs
        """
        return self._request('GET', '/api/v1/jobs', params=params)

    def get_jobs_schedules(self, params=None):
        """GET /api/v1/jobs/schedules
        """
        return self._request('GET', '/api/v1/jobs/schedules', params=params)

    def put_jobs_schedules_by_scheduled_job_id(self, scheduled_job_id, params=None, json=None):
        """PUT /api/v1/jobs/schedules/{scheduled_job_id}
        """
        return self._request('PUT', f'/api/v1/jobs/schedules/{_p(scheduled_job_id)}', params=params, json=json)

    def post_jobs_schedules_by_scheduled_job_id_run(self, scheduled_job_id, params=None, json=None):
        """POST /api/v1/jobs/schedules/{scheduled_job_id}/run
        """
        return self._request('POST', f'/api/v1/jobs/schedules/{_p(scheduled_job_id)}/run', params=params, json=json)

    def get_jobs_stats(self, params=None):
        """GET /api/v1/jobs/stats
        """
        return self._request('GET', '/api/v1/jobs/stats', params=params)

    def get_jobs_by_job_id(self, job_id, params=None):
        """GET /api/v1/jobs/{job_id}
        """
        return self._request('GET', f'/api/v1/jobs/{_p(job_id)}', params=params)

    def post_jobs_by_job_id_cancel(self, job_id, params=None, json=None):
        """POST /api/v1/jobs/{job_id}/cancel
        """
        return self._request('POST', f'/api/v1/jobs/{_p(job_id)}/cancel', params=params, json=json)

    def post_jobs_by_job_id_retry(self, job_id, params=None, json=None):
        """POST /api/v1/jobs/{job_id}/retry
        """
        return self._request('POST', f'/api/v1/jobs/{_p(job_id)}/retry', params=params, json=json)

    def get_metrics_alert_rules(self, params=None):
        """GET /api/v1/metrics/alert-rules
        Requires scope `metrics:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', '/api/v1/metrics/alert-rules', params=params)

    def post_metrics_alert_rules(self, params=None, json=None):
        """POST /api/v1/metrics/alert-rules
        Requires scope `metrics:write` when authenticated with a `dk_` API key.
        """
        return self._request('POST', '/api/v1/metrics/alert-rules', params=params, json=json)

    def get_metrics_alert_rules_ops(self, params=None):
        """GET /api/v1/metrics/alert-rules/ops
        Requires scope `metrics:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', '/api/v1/metrics/alert-rules/ops', params=params)

    def put_metrics_alert_rules_by_rule_id(self, rule_id, params=None, json=None):
        """PUT /api/v1/metrics/alert-rules/{rule_id}
        Requires scope `metrics:write` when authenticated with a `dk_` API key.
        """
        return self._request('PUT', f'/api/v1/metrics/alert-rules/{_p(rule_id)}', params=params, json=json)

    def delete_metrics_alert_rules_by_rule_id(self, rule_id, params=None):
        """DELETE /api/v1/metrics/alert-rules/{rule_id}
        Requires scope `metrics:write` when authenticated with a `dk_` API key.
        """
        return self._request('DELETE', f'/api/v1/metrics/alert-rules/{_p(rule_id)}', params=params)

    def get_metrics_catalog(self, params=None):
        """Discoverable list of queryable metrics for the UI selectors.

        GET /api/v1/metrics/catalog
        Requires scope `metrics:read` when authenticated with a `dk_` API key.
        """
        return self._request('GET', '/api/v1/metrics/catalog', params=params)

    def get_notifications(self, params=None):
        """GET /api/v1/notifications
        """
        return self._request('GET', '/api/v1/notifications', params=params)

    def delete_notifications(self, params=None):
        """DELETE /api/v1/notifications
        """
        return self._request('DELETE', '/api/v1/notifications', params=params)

    def get_notifications_channels(self, params=None):
        """GET /api/v1/notifications/channels
        """
        return self._request('GET', '/api/v1/notifications/channels', params=params)

    def get_notifications_channels_by_channel(self, channel, params=None):
        """GET /api/v1/notifications/channels/{channel}
        """
        return self._request('GET', f'/api/v1/notifications/channels/{_p(channel)}', params=params)

    def put_notifications_channels_by_channel(self, channel, params=None, json=None):
        """PUT /api/v1/notifications/channels/{channel}
        """
        return self._request('PUT', f'/api/v1/notifications/channels/{_p(channel)}', params=params, json=json)

    def post_notifications_channels_by_channel_test(self, channel, params=None, json=None):
        """POST /api/v1/notifications/channels/{channel}/test
        """
        return self._request('POST', f'/api/v1/notifications/channels/{_p(channel)}/test', params=params, json=json)

    def post_notifications_digests_flush(self, params=None, json=None):
        """POST /api/v1/notifications/digests/flush
        """
        return self._request('POST', '/api/v1/notifications/digests/flush', params=params, json=json)

    def get_notifications_events(self, params=None):
        """GET /api/v1/notifications/events
        """
        return self._request('GET', '/api/v1/notifications/events', params=params)

    def get_notifications_preferences(self, params=None):
        """GET /api/v1/notifications/preferences
        """
        return self._request('GET', '/api/v1/notifications/preferences', params=params)

    def put_notifications_preferences(self, params=None, json=None):
        """PUT /api/v1/notifications/preferences
        """
        return self._request('PUT', '/api/v1/notifications/preferences', params=params, json=json)

    def put_notifications_preferences_mute(self, params=None, json=None):
        """PUT /api/v1/notifications/preferences/mute
        """
        return self._request('PUT', '/api/v1/notifications/preferences/mute', params=params, json=json)

    def put_notifications_read_all(self, params=None, json=None):
        """PUT /api/v1/notifications/read-all
        """
        return self._request('PUT', '/api/v1/notifications/read-all', params=params, json=json)

    def get_notifications_unread_count(self, params=None):
        """GET /api/v1/notifications/unread-count
        """
        return self._request('GET', '/api/v1/notifications/unread-count', params=params)

    def get_notifications_by_notification_id(self, notification_id, params=None):
        """GET /api/v1/notifications/{notification_id}
        """
        return self._request('GET', f'/api/v1/notifications/{_p(notification_id)}', params=params)

    def delete_notifications_by_notification_id(self, notification_id, params=None):
        """DELETE /api/v1/notifications/{notification_id}
        """
        return self._request('DELETE', f'/api/v1/notifications/{_p(notification_id)}', params=params)

    def put_notifications_by_notification_id_read(self, notification_id, params=None, json=None):
        """PUT /api/v1/notifications/{notification_id}/read
        """
        return self._request('PUT', f'/api/v1/notifications/{_p(notification_id)}/read', params=params, json=json)

    def get_openapi_json(self, params=None):
        """OpenAPI 3.0 spec, generated live from the url_map — always in sync.

        GET /api/v1/openapi.json
        """
        return self._request('GET', '/api/v1/openapi.json', params=params)

    def get_pipeline_builds(self, params=None):
        """GET /api/v1/pipeline/builds
        """
        return self._request('GET', '/api/v1/pipeline/builds', params=params)

    def post_pipeline_builds(self, params=None, json=None):
        """POST /api/v1/pipeline/builds
        """
        return self._request('POST', '/api/v1/pipeline/builds', params=params, json=json)

    def get_pipeline_builds_by_build_id(self, build_id, params=None):
        """GET /api/v1/pipeline/builds/{build_id}
        """
        return self._request('GET', f'/api/v1/pipeline/builds/{_p(build_id)}', params=params)

    def get_pipeline_builds_by_build_id_failures(self, build_id, params=None):
        """GET /api/v1/pipeline/builds/{build_id}/failures
        """
        return self._request('GET', f'/api/v1/pipeline/builds/{_p(build_id)}/failures', params=params)

    def get_pipeline_builds_by_build_id_screenshots_by_test_index(self, build_id, test_index, params=None):
        """GET /api/v1/pipeline/builds/{build_id}/screenshots/{test_index}
        """
        return self._request('GET', f'/api/v1/pipeline/builds/{_p(build_id)}/screenshots/{_p(test_index)}', params=params)

    def put_pipeline_builds_by_build_id_status(self, build_id, params=None, json=None):
        """PUT /api/v1/pipeline/builds/{build_id}/status
        """
        return self._request('PUT', f'/api/v1/pipeline/builds/{_p(build_id)}/status', params=params, json=json)

    def post_pipeline_builds_by_build_id_tests(self, build_id, params=None, json=None):
        """POST /api/v1/pipeline/builds/{build_id}/tests
        """
        return self._request('POST', f'/api/v1/pipeline/builds/{_p(build_id)}/tests', params=params, json=json)

    def post_pipeline_builds_by_build_id_tests_bulk(self, build_id, params=None, json=None):
        """POST /api/v1/pipeline/builds/{build_id}/tests/bulk
        """
        return self._request('POST', f'/api/v1/pipeline/builds/{_p(build_id)}/tests/bulk', params=params, json=json)

    def get_profiles(self, params=None):
        """GET /api/v1/profiles
        """
        return self._request('GET', '/api/v1/profiles', params=params)

    def post_profiles(self, params=None, json=None):
        """POST /api/v1/profiles
        """
        return self._request('POST', '/api/v1/profiles', params=params, json=json)

    def get_profiles_device_by_device_id(self, device_id, params=None):
        """GET /api/v1/profiles/device/{device_id}
        """
        return self._request('GET', f'/api/v1/profiles/device/{_p(device_id)}', params=params)

    def get_profiles_by_profile_id(self, profile_id, params=None):
        """GET /api/v1/profiles/{profile_id}
        """
        return self._request('GET', f'/api/v1/profiles/{_p(profile_id)}', params=params)

    def put_profiles_by_profile_id(self, profile_id, params=None, json=None):
        """PUT /api/v1/profiles/{profile_id}
        """
        return self._request('PUT', f'/api/v1/profiles/{_p(profile_id)}', params=params, json=json)

    def delete_profiles_by_profile_id(self, profile_id, params=None):
        """DELETE /api/v1/profiles/{profile_id}
        """
        return self._request('DELETE', f'/api/v1/profiles/{_p(profile_id)}', params=params)

    def get_proxy_device_by_device_id(self, device_id, params=None):
        """GET /api/v1/proxy/device/{device_id}
        """
        return self._request('GET', f'/api/v1/proxy/device/{_p(device_id)}', params=params)

    def get_queue_status(self, params=None):
        """GET /api/v1/queue/status
        """
        return self._request('GET', '/api/v1/queue/status', params=params)

    def post_queue_by_name_receive(self, name, params=None, json=None):
        """POST /api/v1/queue/{name}/receive
        """
        return self._request('POST', f'/api/v1/queue/{_p(name)}/receive', params=params, json=json)

    def post_queue_by_name_send(self, name, params=None, json=None):
        """POST /api/v1/queue/{name}/send
        """
        return self._request('POST', f'/api/v1/queue/{_p(name)}/send', params=params, json=json)

    def get_scopes(self, params=None):
        """The assignable scope catalog with descriptions, for integrators.

        GET /api/v1/scopes
        """
        return self._request('GET', '/api/v1/scopes', params=params)

    def get_settings(self, params=None):
        """GET /api/v1/settings
        """
        return self._request('GET', '/api/v1/settings', params=params)

    def put_settings(self, params=None, json=None):
        """PUT /api/v1/settings
        """
        return self._request('PUT', '/api/v1/settings', params=params, json=json)

    def get_users(self, params=None):
        """GET /api/v1/users
        """
        return self._request('GET', '/api/v1/users', params=params)

    def post_users(self, params=None, json=None):
        """POST /api/v1/users
        """
        return self._request('POST', '/api/v1/users', params=params, json=json)

    def get_users_by_user_id(self, user_id, params=None):
        """GET /api/v1/users/{user_id}
        """
        return self._request('GET', f'/api/v1/users/{_p(user_id)}', params=params)

    def put_users_by_user_id(self, user_id, params=None, json=None):
        """PUT /api/v1/users/{user_id}
        """
        return self._request('PUT', f'/api/v1/users/{_p(user_id)}', params=params, json=json)

    def delete_users_by_user_id(self, user_id, params=None):
        """DELETE /api/v1/users/{user_id}
        """
        return self._request('DELETE', f'/api/v1/users/{_p(user_id)}', params=params)

    def get_vault_vaults(self, params=None):
        """GET /api/v1/vault/vaults
        """
        return self._request('GET', '/api/v1/vault/vaults', params=params)

    def post_vault_vaults(self, params=None, json=None):
        """POST /api/v1/vault/vaults
        """
        return self._request('POST', '/api/v1/vault/vaults', params=params, json=json)

    def get_vault_vaults_by_vault_id(self, vault_id, params=None):
        """GET /api/v1/vault/vaults/{vault_id}
        """
        return self._request('GET', f'/api/v1/vault/vaults/{_p(vault_id)}', params=params)

    def delete_vault_vaults_by_vault_id(self, vault_id, params=None):
        """DELETE /api/v1/vault/vaults/{vault_id}
        """
        return self._request('DELETE', f'/api/v1/vault/vaults/{_p(vault_id)}', params=params)

    def get_vault_vaults_by_vault_id_secrets(self, vault_id, params=None):
        """GET /api/v1/vault/vaults/{vault_id}/secrets
        """
        return self._request('GET', f'/api/v1/vault/vaults/{_p(vault_id)}/secrets', params=params)

    def post_vault_vaults_by_vault_id_secrets(self, vault_id, params=None, json=None):
        """POST /api/v1/vault/vaults/{vault_id}/secrets
        """
        return self._request('POST', f'/api/v1/vault/vaults/{_p(vault_id)}/secrets', params=params, json=json)

    def delete_vault_vaults_by_vault_id_secrets_by_key(self, vault_id, key, params=None):
        """DELETE /api/v1/vault/vaults/{vault_id}/secrets/{key}
        """
        return self._request('DELETE', f'/api/v1/vault/vaults/{_p(vault_id)}/secrets/{_p(key)}', params=params)

    def post_vault_vaults_by_vault_id_secrets_by_key_reveal(self, vault_id, key, params=None, json=None):
        """POST /api/v1/vault/vaults/{vault_id}/secrets/{key}/reveal
        """
        return self._request('POST', f'/api/v1/vault/vaults/{_p(vault_id)}/secrets/{_p(key)}/reveal', params=params, json=json)

    def get_workspaces(self, params=None):
        """GET /api/v1/workspaces
        """
        return self._request('GET', '/api/v1/workspaces', params=params)

    def post_workspaces(self, params=None, json=None):
        """POST /api/v1/workspaces
        """
        return self._request('POST', '/api/v1/workspaces', params=params, json=json)

    def get_workspaces_by_workspace_id(self, workspace_id, params=None):
        """GET /api/v1/workspaces/{workspace_id}
        """
        return self._request('GET', f'/api/v1/workspaces/{_p(workspace_id)}', params=params)

    def put_workspaces_by_workspace_id(self, workspace_id, params=None, json=None):
        """PUT /api/v1/workspaces/{workspace_id}
        """
        return self._request('PUT', f'/api/v1/workspaces/{_p(workspace_id)}', params=params, json=json)

    def delete_workspaces_by_workspace_id(self, workspace_id, params=None):
        """DELETE /api/v1/workspaces/{workspace_id}
        """
        return self._request('DELETE', f'/api/v1/workspaces/{_p(workspace_id)}', params=params)

    def get_workspaces_by_workspace_id_members(self, workspace_id, params=None):
        """GET /api/v1/workspaces/{workspace_id}/members
        """
        return self._request('GET', f'/api/v1/workspaces/{_p(workspace_id)}/members', params=params)

    def post_workspaces_by_workspace_id_members(self, workspace_id, params=None, json=None):
        """POST /api/v1/workspaces/{workspace_id}/members
        """
        return self._request('POST', f'/api/v1/workspaces/{_p(workspace_id)}/members', params=params, json=json)

    def put_workspaces_by_workspace_id_members_by_user_id(self, workspace_id, user_id, params=None, json=None):
        """PUT /api/v1/workspaces/{workspace_id}/members/{user_id}
        """
        return self._request('PUT', f'/api/v1/workspaces/{_p(workspace_id)}/members/{_p(user_id)}', params=params, json=json)

    def delete_workspaces_by_workspace_id_members_by_user_id(self, workspace_id, user_id, params=None):
        """DELETE /api/v1/workspaces/{workspace_id}/members/{user_id}
        """
        return self._request('DELETE', f'/api/v1/workspaces/{_p(workspace_id)}/members/{_p(user_id)}', params=params)
