#!/usr/bin/env python3
"""Generate ``devicekit_cli/client.py`` from the DeviceKit OpenAPI spec.

Reads the spec from a file (default: ``openapi.snapshot.json`` next to this script)
or fetches it live with ``--url http://127.0.0.1:5050/api/v1/openapi.json``, then
writes one Python method per (path, HTTP method) pair onto a ``DeviceKitClient``
class. Naming is deterministic and derived from the path alone:

    strip ``/api/v1`` -> replace ``/{x}`` segments with ``_by_<x>`` -> join the
    remaining segments with ``_`` -> prefix the HTTP verb.

    GET  /api/v1/devices                          -> get_devices
    GET  /api/v1/devices/{device_id}/diagnostics  -> get_devices_by_device_id_diagnostics
    POST /api/v1/automations/{automation_id}/run  -> post_automations_by_automation_id_run
    GET  /api/v1                                  -> get_index

Usage:
    python generate_client.py                       # from openapi.snapshot.json
    python generate_client.py path/to/spec.json     # from another snapshot
    python generate_client.py --url http://127.0.0.1:5050/api/v1/openapi.json
"""
import argparse
import json
import keyword
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
DEFAULT_SPEC = HERE / 'openapi.snapshot.json'
DEFAULT_OUT = HERE / 'devicekit_cli' / 'client.py'

# Methods emitted in this fixed order so regeneration is deterministic.
HTTP_METHODS = ('get', 'post', 'put', 'patch', 'delete')

# Arg names that would shadow the method's own keyword params (or Python keywords).
RESERVED = {'self', 'params', 'json'}

HEADER = '''\
# GENERATED by generate_client.py — do not edit
"""Python client for the DeviceKit ``/api/v1`` surface.

Generated from the OpenAPI spec ({info[title]!r}, api version {info[version]}).
Regenerate with ``python cli/generate_client.py`` (see that script for options).

Auth: pass a scoped ``dk_`` API key (sent as ``X-API-Key``) or leave it unset when
the backend runs in solo/dev mode. Errors surface as :class:`DeviceKitApiError`
carrying the HTTP status and the server's ``{{'error': ...}}`` message.
"""
from urllib.parse import quote

import requests

__all__ = ['DeviceKitClient', 'DeviceKitApiError']


def _p(value):
    """Encode one path parameter."""
    return quote(str(value), safe='')


class DeviceKitApiError(Exception):
    """Non-2xx API response: ``.status`` (int) and ``.message`` (server error text)."""

    def __init__(self, status, message):
        super().__init__(f'HTTP {{status}}: {{message}}')
        self.status = status
        self.message = message


class DeviceKitClient:
    """Thin requests-based client; one method per documented (path, verb) pair."""

    def __init__(self, base_url='http://127.0.0.1:5050', api_key=None, timeout=60):
        self.base_url = base_url.rstrip('/')
        self.timeout = timeout
        self.session = requests.Session()
        self.session.headers['Accept'] = 'application/json'
        if api_key:
            self.session.headers['X-API-Key'] = api_key

    def _request(self, method, path, params=None, json=None):
        resp = self.session.request(method, self.base_url + path, params=params,
                                    json=json, timeout=self.timeout)
        try:
            body = resp.json()
        except ValueError:
            body = None
        if not 200 <= resp.status_code < 300:
            if isinstance(body, dict) and body.get('error'):
                message = body['error']
            else:
                message = (resp.text or resp.reason or '').strip()[:300]
            raise DeviceKitApiError(resp.status_code, message)
        return body if body is not None else resp.text
'''


def _sanitize(token):
    """A path segment or param name -> identifier-safe token (``openapi.json`` -> ``openapi_json``)."""
    return re.sub(r'[^0-9a-zA-Z]+', '_', token).strip('_')


def method_name(http_method, path):
    """Deterministic client-method name for a (verb, /api/v1 path) pair."""
    rest = path[len('/api/v1'):] if path.startswith('/api/v1') else path
    parts = []
    for seg in rest.split('/'):
        if not seg:
            continue
        m = re.fullmatch(r'\{(.+)\}', seg)
        parts.append(f'by_{_sanitize(m.group(1))}' if m else _sanitize(seg))
    return f"{http_method}_{'_'.join(parts) or 'index'}"


def path_params(path):
    """Path parameter names in order of appearance."""
    return re.findall(r'\{([^{}]+)\}', path)


def _arg_name(param):
    name = _sanitize(param)
    if name in RESERVED or keyword.iskeyword(name) or not name:
        name += '_'
    return name


def _path_expr(path):
    """Python expression that rebuilds ``path`` with encoded runtime params."""
    if '{' not in path:
        return repr(path)
    expr = path.replace('{', '{_p(').replace('}', ')}')
    for param in path_params(path):
        expr = expr.replace(f'_p({param})', f'_p({_arg_name(param)})')
    return "f'" + expr + "'"


def _docstring(op, http_method, path):
    operation = f'{http_method.upper()} {path}'
    summary = (op.get('summary') or operation).strip()
    lines = [summary]
    if summary != operation:
        lines += ['', operation]
    scope = op.get('x-required-scope')
    if scope:
        lines.append(f'Requires scope `{scope}` when authenticated with a `dk_` API key.')
    text = '\n'.join(f'        {line}'.rstrip() for line in lines).lstrip()
    text = text.replace('\\', '\\\\').replace('"""', "'''")
    return f'        """{text}\n        """'


def render_method(http_method, path, op):
    name = method_name(http_method, path)
    args = [_arg_name(p) for p in path_params(path)]
    has_body = http_method in ('post', 'put', 'patch') or 'requestBody' in op
    sig = ['self'] + args + ['params=None'] + (['json=None'] if has_body else [])
    call = [f"'{http_method.upper()}'", _path_expr(path), 'params=params']
    if has_body:
        call.append('json=json')
    return (
        f"    def {name}({', '.join(sig)}):\n"
        f"{_docstring(op, http_method, path)}\n"
        f"        return self._request({', '.join(call)})\n"
    )


def generate(spec):
    """Full source of client.py for ``spec``; raises on method-name collisions."""
    chunks = [HEADER.format(info=spec.get('info', {'title': 'DeviceKit', 'version': '?'}))]
    seen = {}
    count = 0
    for path in sorted(spec.get('paths', {})):
        item = spec['paths'][path]
        for http_method in HTTP_METHODS:
            if http_method not in item:
                continue
            name = method_name(http_method, path)
            if name in seen:
                raise ValueError(f'method name collision: {name!r} from '
                                 f'{seen[name]} and {http_method.upper()} {path}')
            seen[name] = f'{http_method.upper()} {path}'
            chunks.append('\n' + render_method(http_method, path, item[http_method]))
            count += 1
    return ''.join(chunks), count


def load_spec(args):
    if args.url:
        from urllib.request import urlopen  # stdlib: the generator has no hard deps
        with urlopen(args.url) as resp:
            return json.load(resp)
    with open(args.spec, encoding='utf-8') as f:
        return json.load(f)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('spec', nargs='?', default=str(DEFAULT_SPEC),
                        help='path to an OpenAPI JSON snapshot (default: %(default)s)')
    parser.add_argument('--url', help='fetch the spec from a running backend instead, '
                                      'e.g. http://127.0.0.1:5050/api/v1/openapi.json')
    parser.add_argument('--out', default=str(DEFAULT_OUT),
                        help='output module path (default: %(default)s)')
    args = parser.parse_args(argv)

    spec = load_spec(args)
    source, count = generate(spec)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(source, encoding='utf-8', newline='\n')
    print(f'wrote {out} ({count} methods from {len(spec.get("paths", {}))} paths)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
