"""initial schema

Revision ID: f71bdf167605
Revises: 
Create Date: 2026-07-10 00:10:21.116824
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f71bdf167605'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_devices',
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('serial', sa.String(), nullable=True),
    sa.Column('info', sa.JSON(), nullable=True),
    sa.Column('state', sa.JSON(), nullable=True),
    sa.Column('registered_at', sa.Float(), nullable=False),
    sa.Column('last_heartbeat', sa.Float(), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('device_id')
    )
    with op.batch_alter_table('agent_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_devices_serial'), ['serial'], unique=False)

    op.create_table('automation_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('automation_id', sa.String(), nullable=True),
    sa.Column('automation_name', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.Float(), nullable=True),
    sa.Column('finished_at', sa.Float(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('completed_steps', sa.Integer(), nullable=True),
    sa.Column('current_step_index', sa.Integer(), nullable=True),
    sa.Column('step_results', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('self_heal', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_runs_automation_id'), ['automation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_runs_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_runs_started_at'), ['started_at'], unique=False)

    op.create_table('automation_schedules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('automation_id', sa.String(), nullable=True),
    sa.Column('automation_name', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('interval_minutes', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.Float(), nullable=True),
    sa.Column('next_run_at', sa.Float(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automation_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_schedules_automation_id'), ['automation_id'], unique=False)

    op.create_table('automations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debug_bundles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('trigger', sa.String(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('files', sa.JSON(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('generation_ms', sa.Integer(), nullable=True),
    sa.Column('ai_analysis', sa.JSON(), nullable=True),
    sa.Column('zip_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('debug_bundles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_debug_bundles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_debug_bundles_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_debug_bundles_trigger'), ['trigger'], unique=False)

    op.create_table('device_groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('device_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_tags',
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('saved_queries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stream_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=True),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.Float(), nullable=True),
    sa.Column('stopped_at', sa.Float(), nullable=True),
    sa.Column('frame_count', sa.Integer(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('frames_dir', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stream_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stream_sessions_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stream_sessions_started_at'), ['started_at'], unique=False)

    op.create_table('visual_baselines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('automation_id', sa.String(), nullable=True),
    sa.Column('step_index', sa.Integer(), nullable=True),
    sa.Column('device_model', sa.String(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('image_data', sa.LargeBinary(), nullable=True),
    sa.Column('image_size', sa.Integer(), nullable=True),
    sa.Column('mask_regions', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visual_baselines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visual_baselines_automation_id'), ['automation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visual_baselines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visual_baselines_automation_id'))

    op.drop_table('visual_baselines')
    with op.batch_alter_table('stream_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stream_sessions_started_at'))
        batch_op.drop_index(batch_op.f('ix_stream_sessions_device_id'))

    op.drop_table('stream_sessions')
    op.drop_table('saved_queries')
    op.drop_table('device_tags')
    op.drop_table('device_groups')
    with op.batch_alter_table('debug_bundles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debug_bundles_trigger'))
        batch_op.drop_index(batch_op.f('ix_debug_bundles_device_id'))
        batch_op.drop_index(batch_op.f('ix_debug_bundles_created_at'))

    op.drop_table('debug_bundles')
    op.drop_table('automations')
    with op.batch_alter_table('automation_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_schedules_automation_id'))

    op.drop_table('automation_schedules')
    with op.batch_alter_table('automation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_automation_runs_device_id'))
        batch_op.drop_index(batch_op.f('ix_automation_runs_automation_id'))

    op.drop_table('automation_runs')
    with op.batch_alter_table('agent_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_devices_serial'))

    op.drop_table('agent_devices')
    # ### end Alembic commands ###
